services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    image: oms-backend:latest
    container_name: oms-backend
    environment:
      - PORT=3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    image: oms-frontend:latest
    container_name: oms-frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    restart: unless-stopped

